# inherit_from: .rubocop_todo.yml
# Stylistic choices of this cookbook.

# We still have HashRockets in a lot of places, ignore them.
Style/HashSyntax:
  Enabled: false

# We're fine with multi-line blocks defined with `{...}` instead of `do...end`
Style/BlockDelimiters:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i': '[]'
    '%w': '[]'

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

# Only enforce a wordlist for 5 or longer lists.
Style/WordArray:
  MinSize: 5
