Chef/Modernize/UnnecessaryDependsChef14:
  # We want to keep compatiblity with Chef < 14
  Enabled: false

Chef/Deprecations/ChefHandlerUsesSupports:
  # We want to keep compatiblity with Chef < 14
  Enabled: false
