# inherit_from: .rubocop_todo.yml
# Stylistic choices of this cookbook.

# We still have HashRockets in a lot of places, ignore them.
Style/HashSyntax:
  Enabled: false

# We're fine with multi-line blocks defined with `{...}` instead of `do...end`
Style/BlockDelimiters:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i': '[]'
    '%w': '[]'

Style/TrailingCommaInArrayLiteral:
  # TODO: Uncoment this and open a massive PR which adds all the trailing commas
  #EnforcedStyleForMultiline: comma
  Enabled: false

Style/TrailingCommaInHashLiteral:
  # TODO: Uncoment this and open a massive PR which adds all the trailing commas
  #EnforcedStyleForMultiline: comma
  Enabled: false

# Only enforce a wordlist for 5 or longer lists.
Style/WordArray:
  MinSize: 5

ChefDeprecations/DeprecatedChefSpecPlatform:
  # We want to keep compatiblity with old distros/platforms
  Enabled: false

ChefModernize/UnnecessaryDependsChef14:
  # We want to keep compatiblity with Chef < 14
  Enabled: false

ChefDeprecations/ChefHandlerUsesSupports:
  # We want to keep compatiblity with Chef < 14
  Enabled: false

ChefStyle/TrueClassFalseClassResourceProperties:
  Enabled: false
