source 'https://rubygems.org'

gem 'rake'
gem 'chef', '= 14.10.9'
gem 'foodcritic', '~> 11.4.0'
gem 'cucumber-core', '~> 3.2.1'
gem 'chefspec'
gem 'cookstyle'
gem 'coveralls', '~> 0.8.19'
gem 'test-kitchen'
gem 'json_spec', '~> 1.1.4'
gem 'kitchen-vagrant'
gem 'kitchen-docker', '~> 2.3.0'
gem 'berkshelf', '~> 6.3'
gem 'rubocop', '~> 0.49.1'
