name              'test'
maintainer        'Datadog'
maintainer_email  'package@datadoghq.com'
license           'Apache-2.0'
version           '0.0.1'
description       'Tests cookbooks'
depends           'datadog'
