source 'https://rubygems.org'

chef_version = ENV.fetch('CHEF_VERSION', '14.10.9')

if RUBY_VERSION < '2.6'
  gem 'net-ssh', '~> 6.1.0'
  gem 'public_suffix', '~> 4.0.0'
  gem 'json_spec', '~> 1.1.5'
end

if Gem::Version.new(chef_version) > Gem::Version.new('16.0.0') && RUBY_VERSION < '2.7'
  gem 'train-core', '~> 3.9.0'
end
