source 'https://rubygems.org'

if RUBY_VERSION < '2.6'
  gem 'net-ssh', '~> 6.1.0'
  gem 'public_suffix', '~> 4.0.0'
  gem 'json_spec', '~> 1.1.5'
end

if Gem.loaded_specs["chef"].version > Gem::Version.new('16.0.0') and RUBY_VERSION < '2.7'
  gem 'train-core', '~> 3.9.0'
end
